name: Deploy Hugo site to Cloudflare Workers

on:
  push:
    branches:
      - main # Change if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo --minify

      # If you need to move/copy files, e.g., if Cloudflare Worker needs a specific structure, do it here

      - name: Publish to Cloudflare Workers
        run: npx wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}